version: '3.8'

services:
 backend:
   image: jyothiswaroopmakena0608/backend:latest
   build:
     context: ./backend # Path to the backend Dockerfile
   ports:
     - "8080:8080"


 backend2:
   image: jyothiswaroopmakena0608/backend2:latest
   build:
     context: ./backend # Path to the backend Dockerfile
   ports:
     - "8081:8080"


 auth-backend:
   image: jyothiswaroopmakena0608/auth-backend:latest
   build:
     context: ./backend-auth # Path to the backend Dockerfile
   ports:
     - "5000:5000" 


 frontend1:
   image: jyothiswaroopmakena0608/frontend1:latest
   build:
     context: ./frontend # Path to the frontend Dockerfile
   ports:
     - "3000:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend

 frontend2:
   image: jyothiswaroopmakena0608/frontend2:latest
   build:
     context: ./frontend # Path to the frontend Dockerfile
   ports:
     - "3001:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend


 frontend3:
   image: jyothiswaroopmakena0608/frontend3:latest
   build:
     context: ./frontend-2 # Path to the frontend Dockerfile
   ports:
     - "3002:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend